// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Q2fBEeSXXfKDmjCNU5t0DQQmK_3Vvt4',
    appId: '1:353454995000:web:49e2cd50d8a937ebbc98cd',
    messagingSenderId: '353454995000',
    projectId: 'daktarpai-18fbf',
    authDomain: 'daktarpai-18fbf.firebaseapp.com',
    storageBucket: 'daktarpai-18fbf.firebasestorage.app',
    measurementId: 'G-N80XYFECG5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6qvX-h6WAD23vv3HH6rA3S9BY74Fl8Pk',
    appId: '1:353454995000:ios:2ff9f3dcb00a8214bc98cd',
    messagingSenderId: '353454995000',
    projectId: 'daktarpai-18fbf',
    storageBucket: 'daktarpai-18fbf.firebasestorage.app',
    iosBundleId: 'com.example.daktarpi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Q2fBEeSXXfKDmjCNU5t0DQQmK_3Vvt4',
    appId: '1:353454995000:web:768e02bef2de7231bc98cd',
    messagingSenderId: '353454995000',
    projectId: 'daktarpai-18fbf',
    authDomain: 'daktarpai-18fbf.firebaseapp.com',
    storageBucket: 'daktarpai-18fbf.firebasestorage.app',
    measurementId: 'G-TRM9HVXGKB',
  );

}